# Generated by Django 5.1 on 2024-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile_mark_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mark',
            field=models.BooleanField(default=False, verbose_name='Согласие на отправку уведомлений по почте'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол'),
        ),
    ]
