# Generated by Django 5.1 on 2024-09-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
