# Generated by Django 5.1 on 2024-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_news_options_alter_profile_options_news_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(default='None', max_length=200, verbose_name='Название статьи'),
        ),
    ]
