# Generated by Django 5.1 on 2024-09-15 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_news_author_alter_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 2, 23, 14, 319560), verbose_name='Время публикации статьи'),
        ),
    ]
