# Generated by Django 5.1 on 2024-09-19 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_news_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Без темы', max_length=200, verbose_name='Тема письма')),
                ('mail', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('text', models.TextField(verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 2, 16, 12, 592770), verbose_name='Время публикации статьи'),
        ),
    ]
